functionsDirectory = "/Users/huangyu/Documents/Qoder/2026-07-15/chat-2/french-learner/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/huangyu/Documents/Qoder/2026-07-15/chat-2/french-learner/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'using pre-built dist'"
functions = "/Users/huangyu/Documents/Qoder/2026-07-15/chat-2/french-learner/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/tts"
to = "/.netlify/functions/tts"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]